# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory inside the container
WORKDIR /app

# Copy your code and requirements file into the container
COPY . .

# Install required packages
RUN pip install -r requirements.txt

# Install Jupyter Notebook
RUN pip install notebook

# Expose the port that Jupyter uses
EXPOSE 8888

# Specify the command to run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
