
# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory inside the container
WORKDIR /app

# Copy your code and requirements file into the container
COPY . .

# Install required packages
RUN pip install -r requirements.txt

# Specify the command to run when the container starts
CMD ["python", "C:\Users\apaar\Desktop\WobotAssignment\yolo.ipynb"]

